mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

mysite/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    # path('', views.index, name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name="detail"),
    # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name="results"),
    # ex: /polls/5/vote/

    # Generic Views
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name="vote")
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    questionText = models.CharField(max_length=200)
    pubDate = models.DateTimeField('date published')
    def __str__(self) -> str:return self.questionText
    def wasPublishedRecently(self):
        return self.pubDate >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choiceText = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self) -> str:return self.choiceText

mysite/polls/views.py
from django.http.response import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latestQuestionList"

    def get_queryset(self):
        """return the last 5 published questions"""
        return Question.objects.order_by('-pubDate')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

# Create your views here.
def index(request):
    latestQuestions = Question.objects.order_by("-pubDate")[:5]
    return render(request, "polls/index.html", {
        "latestQuestions": latestQuestions
    })

def detail(request, question_id):
    # Shortened version
    question = get_object_or_404(Question, pk=question_id)
    # syntax     get_object_or_404(Model, model attribute kwargs to check if wanted object exists) uses .get()
    #            get_list_of_404() same but uses .filter and returns list
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {
        'question': question
    })

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {
        "question": question
    })

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # redisplay the question voting form 
        return render(request, 'polls/detail.html', {
            "question": question,
            "error_message": "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POSTdara. This prevents data from being posted twice if a 
        # user hits the back button.
        return HttpResponseRedirect(reverse('polls:results',args=(question.id)))

mysite/polls/templates/polls/detail.html
{% extends 'polls/layout.html' %}

{% block body %}
    <h1>{{ question.questionText }}</h1>

    {% if error_message %} 
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}"
                value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choiceText }}</label>
            <p>{{ choice.votes }}</p>
        {% endfor %}
        <input type="submit" value="Vote">
    </form>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/layout.html' %}

{% block body %}

    {% if latestQuestions %}
        <ul>
            {% for question in latestQuestions %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.questionText }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'layout.html' %}

{% block body %}

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choiceText }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}"> Vote again?</a>

{% endblock %}