fccDjango/Blog/urls.py
from django.urls import path
from .views import (
    # views
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView
)

app_name = "blog"
urlpatterns = [
    path('', ArticleListView.as_view(), name="article-list"),
    path('<int:id>', ArticleDetailView.as_view(), name="article-detail"), #can customize lookup
    path('create/', ArticleCreateView.as_view(), name="article-create"),
    path('<int:id>/update/', ArticleUpdateView.as_view(), name="article-update"),
    path('<int:id>/delete/', ArticleDeleteView.as_view(), name="article-delete")
]
# class based views look for a specific template
# <app name>/<model name>_<generic view name>.html
# blog/modelname_list.html

fccDjango/fccDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Blog/', include("Blog.urls"))
]

fccDjango/Blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Article(models.Model):
    title   = models.CharField(max_length=120)
    content = models.TextField()
    active  = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("blog:article-detail", kwargs={"id": self.id})

fccDjango/Blog/forms.py
from django import forms
from django.core.files.utils import FileProxyMixin

from .models import Article


class ArticleForm(forms.ModelForm):
    title   = forms.CharField(
                        label="Article Title",
                        widget=forms.TextInput(
                            attrs={
                               "placeholder": "Article Title"
                            }
                        ))
    content = forms.CharField(
                        widget=forms.Textarea(
                            attrs={
                                "placeholder": "blog content goes here",
                                "class": "class-names mb-2",
                                "id": "createArticleFormTextbox",
                                "rows": 10,
                                "cols": 20
                            })) #change to text area through widget prop, .TextField doesn't exist for form
    class Meta:
        model = Article
        fields = [
            'title',
            'content',
            'active'
        ]

    # def clean_article(self, *args, **kwargs):
    #     title = self.cleaned_data.get("title")
    #     wanted = "whatever"
    #     if not wanted in title:
    #         raise forms.ValidationError(f"title must include{wanted}")
    #     if not "somethingElse" in title:
    #         raise forms.ValidationError("must include somethingElse")
    #     return title

    # def clean_email(self, *args, **kwargs):
    #     email = self.cleaned_data.get("email")
    #     if not email.endswith(".edu"):
    #         raise forms.ValidationError("not a valid student email")
    #     return email

class RawArticleForm(forms.Form):
    title   = forms.CharField(
                        label="Article Title",
                        widget=forms.TextInput(
                            attrs={
                               "placeholder": "Article Title"
                            }
                        ))
    article = forms.CharField(
                        widget=forms.Textarea(
                            attrs={
                                "placeholder": "blog content goes here",
                                "class": "class-names mb-2",
                                "id": "createArticleFormTextbox",
                                "rows": 10,
                                "cols": 20
                            })) #change to text area through widget prop, .TextField doesn't exist for form

# class CourseModelForm(forms.ModelForm):
#     class Meta:
#         model = Course
#         fields = [
#             'title'
#         ]

fccDjango/Blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    CreateView, DetailView, ListView, UpdateView, DeleteView
)

from .models import Article
from .forms import ArticleForm, RawArticleForm
# Create your views here.

class ArticleListView(ListView):
    queryset = Article.objects.all()
    template_name = "Blog/article_list.html"

class ArticleCreateView(CreateView):
    form_class = ArticleForm
    queryset = Article.objects.all()
    template_name = "Blog/article_create.html"

    def form_valid(self, form):
        print(form.cleaned_data())
        return super().form_valid(form)

    # change where you want it to go
    # option 1: set var
    success_url = '/'
    # option 2: def the var
    # def get_success_url(self) -> str:
    #     return '/'

# Raw Create View
class CourseCreateView(View):
    template_name = "Blog/course_create.html"
    
    def get(self, request, id=None, *args, **kwargs):
        # GET method
        context = {}
        return render(request, self.template_name, context)
    
    def post(self, request, id=None, *args, **kwargs):
        # POST method
        context = {}
        
    

class ArticleUpdateView(UpdateView):
    form_class = ArticleForm
    queryset = Article.objects.all()
    template_name = "Blog/article_update.html"

    def form_valid(self, form):
        print(form.cleaned_data())
        return super().form_valid(form)

    # same as create except here we're grabbing an instance of the object to change it
    def get_object(self):
        id_ = self.kwargs.get("id") #takes in given kwarg from the url regex, can customize
        return get_object_or_404(Article, id=id_)


# the primary function of a detail view, is to render a template from a specific object
class ArticleDetailView(DetailView):
    # queryset limits choices available for that detailview
    queryset = Article.objects.all()
    template_name = "Blog/article_detail.html"

    def get_object(self):
        id_ = self.kwargs.get("id") #takes in given kwarg from the url regex, can customize
        return get_object_or_404(Article, id=id_)

class ArticleDeleteView(DeleteView):
    # queryset limits choices available for that detailview
    queryset = Article.objects.all()
    template_name = "Blog/article_delete.html"

    def get_object(self):
        id_ = self.kwargs.get("id") #takes in given kwarg from the url regex, can customize
        return get_object_or_404(Article, id=id_)

def article_create_view(request):
    form = RawArticleForm() #initialize form, render for get
    
    # check if method is post
    if request.method == "POST":
        # take in the data the user submitted and save it as a form
        form = RawArticleForm(request.POST) #render for post request
        # check if form data is valid server-side
        if form.is_valid():
            # create new DB object from form. ** turns it into args to pass
            Article.objects.create(**form.cleaned_data)
        else:
            return render(request, 'Blog/article_create.html', {
                "createArticleForm": form
            })

    context = {
        "createArticleForm": form
    }
    return render(request, 'Blog/article_create.html', context)

def article_create_view2(request):
    form = ArticleForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = ArticleForm()
    context = {
        "createArticleForm": form
    }
    return render(request, 'Blog/article_create.html', context)

fccDjango/Blog/templates/Blog/article-delete.html
{% extends 'Blog/layout.html' %}

{% block title %}
    Delete: 
{% endblock %}

{% block body %}

{% endblock %}

fccDjango/Blog/templates/Blog/article_create.html
{% extends 'Blog/layout.html' %}

{% block body %}

<h1 class="mt-1">Create New Article</h1>

<form action="{% url 'blog:article-create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock %}

fccDjango/Blog/templates/Blog/article_detail.html
{% extends 'Blog/layout.html' %}

{% block title %}
    Article: {{ object.title }}
{% endblock %}

{% block body %}
    <h1>{{ object.title }}</h1>
    <p>{{ object.content }}</p>
{% endblock %}

fccDjango/Blog/templates/Blog/article_list.html
{% extends 'Blog/layout.html' %}

{% block body %}
    {% for instance in object_list %}
    <p>{{ instance.id }} - <a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></p>

    {% endfor %}
{% endblock %}

fccDjango/Blog/templates/Blog/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    {% include 'Blog/nav.html' %}
    
    {% block body %}
    {% endblock %}
    
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

fccDjango/Blog/templates/Blog/nav.html
<nav class="navbar mb-1 navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog:article-list' %}">ARTICLES</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:article-list' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:article-create' %}">Create</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>