wiki/wiki/encyclopedia/urls.py
from django.urls import path

from .views import (
    randomPageView, WikiListView,
    WikiDetailView,
    WikiCreateView,
    WikiUpdateView,
    WikiDeleteView,
    WikiSearchView
)

app_name = "wiki"
urlpatterns = [
    # ex: /wiki/
    path('', WikiListView.as_view(), name="wiki-list"),
    path('wiki/<str:wikiEntry>/', WikiDetailView.as_view(), name="wiki-detail"),
    path('wiki/<str:wikiEntry>/update', WikiUpdateView.as_view(), name="wiki-update"),
    path('wiki/<str:wikiEntry>/delete', WikiDeleteView.as_view(), name="wiki-delete"),
    path('wiki/create', WikiCreateView.as_view(), name="wiki-create"),
    path('wiki/search_results', WikiSearchView.as_view(), name="wiki-search"),
    path('random/', randomPageView, name="wiki-random" )
    # path('wiki/<str:wikiEntry>/update')
    # ex: /wiki/EntryPageName
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include("encyclopedia.urls"))
]

wiki/wiki/encyclopedia/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

import datetime

# Create your models here.
class Entry(models.Model):
    title = models.CharField(max_length=64, unique=True)
    def __str__(self):
        return f"{self.title}"
    content = models.TextField()
    # lastEditedDate = models.DateTimeField('date edited')

    # allows creation of new entry to redirect to new entry page
    # called by CreateView and UpdateView generic classes
    def get_absolute_url(self):
        return reverse("wiki:wiki-detail", kwargs={"wikiEntry": self.title})

wiki/wiki/encyclopedia/forms.py
from django import forms

from .models import Entry

class SearchForm(forms.Form):
    q = forms.CharField(label="Search", max_length=50)

class EntryForm(forms.ModelForm):
    title   = forms.CharField(
                        label="Article Title",
                        widget=forms.TextInput(
                            attrs={
                               "placeholder": "Article Title"
                            }
                        ))
    content = forms.CharField(
                        widget=forms.Textarea(
                            attrs={
                                "placeholder": "wiki content goes here",
                                "class": "",
                                "id": "createArticleFormTextbox"
                                # "rows": 5,
                                # "cols": 4
                            })) #change to text area through widget prop, .TextField doesn't exist for form
    class Meta:
        model = Entry
        fields = [
            'title',
            'content'
        ]
    
    # custom form validation
    # def clean_<myFieldName>():
    # def clean_title(self, *args, **kwargs):
    #     title = self.cleaned_data.get("title")
    #     if not "cfe" in title:
    #         raise forms.ValidationError("this is not a valid title! must contain 'cfe' ")
    #     if not "whatever" in title:
    #         raise forms.ValidationError("error: title must contain 'whatever' ")
    #     return title

    # def clean_email(self, *args, **kwargs):
    #     email = self.cleaned_data.get("email")
    #     if not email.contains(".edu"):
    #         raise form.ValidationError("must be a student email address!")
    #     return email

wiki/wiki/encyclopedia/views.py
import re
import random as rn
from django.db.models import query
from django.db.models.query_utils import Q
from django.http import request, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django import forms
from django.views.generic import ListView, FormView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.urls import reverse

from . import util
from .models import Entry
from .forms import EntryForm, SearchForm

import markdown2


# can separate forms into forms.py and just import them, same as models
class WikiListView(ListView):
    queryset = Entry.objects.all()
    template_name = "encyclopedia/index.html"
    context_object_name = "allEntries"
    # form_class = SearchForm
    
    # def get(self, request, *args, **kwargs):
    #     context = {
    #         "allEntries": self.queryset
    #     }
    #     return render(request, self.template_name, context)

# class WikiLayoutView(FormView):
#     template_name = "encyclopedia/layout.html"
#     form_class = SearchForm

class WikiDetailView(DetailView):
    template_name = "encyclopedia/wiki_detail.html"
    queryset = Entry.objects.all()
    context_object_name = "entryTitle"

    # Override default regex arg passed to url to allow for wikiEntry instead of just pk
    def get_object(self):
        x = self.kwargs.get("wikiEntry")
        return get_object_or_404(Entry, title=x)

    def get_context_data(self, *args, **kwargs):
        context = super(WikiDetailView, self).get_context_data(*args,**kwargs)
        # add extra field
        z = Entry.objects.get(title=self.kwargs.get("wikiEntry"))
        context["entryHTML"] = markdown2.markdown(z.content)
        return context

def randomPageView(request):
    # Get total # of entries
    entryCount = Entry.objects.all().count()
    
    # Initialize set of unique Entry PKs
    entryPKs = []

    # Get all PKs (this excludes deleted ones)
    for entry in Entry.objects.all():
        currentPK = entry.pk
        entryPKs.append(currentPK)

    # Select a random Entry obect
    randomEntry = Entry.objects.get(pk=rn.choice(entryPKs))

    # Redirect to a the randomly selected detail page
    return redirect('wiki:wiki-detail', wikiEntry=randomEntry.title)


class WikiCreateView(CreateView):
    template_name = "encyclopedia/wiki_create.html"
    queryset = Entry.objects.all()
    form_class = EntryForm

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class WikiUpdateView(UpdateView):
    template_name = "encyclopedia/wiki_update.html"
    queryset = Entry.objects.all()
    form_class = EntryForm

    def get_object(self):
        x = self.kwargs.get("wikiEntry")
        return get_object_or_404(Entry, title=x)

class WikiDeleteView(DeleteView):
    template_name = "encyclopedia/wiki_delete.html"

    def get_object(self):
        x = self.kwargs.get("wikiEntry")
        return get_object_or_404(Entry, title=x)
    def get_success_url(self) -> str:
        return reverse('wiki:wiki-list')

class WikiSearchView(ListView):
    template_name = "encyclopedia/wiki_search.html"
    model = Entry
    paginate_by = 25
    context_object_name = "searchResults"

    def get_queryset(self):
        search = self.request.GET.get('q')
        return Entry.objects.filter(Q(title__icontains=search))

    def get(self, request, *args, **kwargs):
        # Check if there is only one entry that matches 
        if len(self.get_queryset()) == 1:
            # Check if it is an exact match, case sensitive
            if self.request.GET.get('q') == self.get_queryset().first().title:
                return redirect('wiki:wiki-detail', wikiEntry=self.get_queryset().first().title)

        context = {"searchResults": self.get_queryset()}
        return render(request, self.template_name, context)


# ##############################################################

wiki/wiki/encyclopedia/templates/encyclopedia/displayEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if entryTitle %}
        {{ entryTitle }}
    {% else %}
        Page Not Found!
    {% endif %}
{% endblock %}

{% block body %}
    {% if entryHTML %}
        {{ entryHTML|safe }}
    {% else %}
        <p>This page does not exist yet.</p>
        <p>Check your spelling or create a new entry!</p>
        <p>?? {{ testPrint }}</p>
    {% endif %}
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {% if allEntries %}
        <h1>All Pages</h1>

        <ul>
            {% for entry in allEntries %}
                <!-- <li><a href="/encyclopedia/{{ entry.title }}">{{ entry.title }}</a></li> -->
                <li><a href="{% url 'wiki:wiki-detail' entry.title %}">{{ entry.title }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <p>no entries yet!</p>
    {% endif %}

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:wiki-search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                    <!-- <input type="submit" value="submit"> -->
                    <!-- {{ form }} -->
                </form>
                <div>
                    <a href="{% url 'wiki:wiki-list' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:wiki-create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:wiki-random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/searchResults.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results: {{ searchedTerm }}
{% endblock %}


{% block body %}

    {% if searchResults %}
        <h3>Search Results</h3>
        <ul>
            {% for result in searchResults %}    
                <li><a href="{% url 'wiki:displayPage' result.title %}">{{ result.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>{{ emptyResults }}</h3>        
    {% endif %}

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/wiki_create.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Create New Entry
{% endblock %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Save">
</form>
    
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/wiki_delete.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Delete: {{ object.title }}?
{% endblock %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    <h2>Do you want to delete the entry: {{ object.title }}</h2>
    <p>
        <input type="submit" value="Yes" />
        <a href="{% url 'wiki:wiki-detail' object.title %}">Cancel</a>
    </p>
</form>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/wiki_detail.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if entryTitle %}
        {{ entryTitle }}
    {% else %}
        Page Not Found!
    {% endif %}
{% endblock %}

{% block body %}
    {% if entryHTML %}
        <h1>{{ entryTitle }}</h1>
        <form action="{% url 'wiki:wiki-update' entryTitle %}">
            <button type="submit">Update</button>
        </form>
        <form action="{% url 'wiki:wiki-delete' entryTitle %}">
            <button type="submit">Delete</button>
        </form>
        {{ entryHTML|safe }}
    {% else %}
        <p>This page does not exist yet.</p>
        <p>Check your spelling or create a new entry!</p>
        <p>?? {{ testPrint }}</p>
    {% endif %}
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/wiki_search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results:
{% endblock %}


{% block body %}

    {% if searchResults %}
        <h3>Search Results</h3>
        <ul>
            {% for result in searchResults %}    
                <li><a href="{% url 'wiki:wiki-detail' result.title %}">{{ result.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No results found</h3>        
    {% endif %}

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/wiki_update.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Update Entry:
{% endblock %}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="Save">
</form>

<h2>Existing Article</h2>


{% endblock %}