lecture3/hello/urls.py
# from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("tony", views.tony, name="tony"),
    path("<str:name>", views.greet, name="greet")
]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

lecture3/newyear/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

lecture3/tasks/urls.py
from django.urls import path
from . import views


app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("addTask", views.addTask, name="addTask")
]

lecture3/hello/models.py
from django.db import models

# Create your models here.

lecture3/newyear/models.py
from django.db import models

# Create your models here.

lecture3/tasks/models.py
from django.db import models

# Create your models here.

lecture3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request,"hello/index.html")

def tony(request):
    return HttpResponse("Hello, Tony!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    }) #optional third argument called the context, all info to provide to the template, variables ie

lecture3/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
# def index(request):
#     now = datetime.datetime.now()
#     if now.month == 1 and now.day == 1:
#         return render(request, "newyear/index.html", {
#             "answer" : "yes".capitalize()
#         })
#     else:
#         return render(request, "newyear/index.html", {
#             "answer" : "no".capitalize()
#         })
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "answer": now.month == 1 and now.day == 1
        # "answer": True
    })

lecture3/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

# tasks = ["foo","bar","baz"]

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    # priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):

    # store tasks inside the users session, so other sessions cant see. sessions determined by cookies
    # check if there are already tasks stored in the session
    if "tasks" not in request.session:
        request.session["tasks"] = []
        #need py manage.py migrate in order to create default tables inside of djangos database
    
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"] #pass in the list of session tasks to the tasks variable to use in the template
        # django template : python variable
    })

def addTask(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST) # contains all of the data that the user submitted when they submitted the form
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            
            return HttpResponseRedirect(reverse("tasks:index")) #figure out what the url of the index url for the tasks app is, and use that
        else:
            return render(request, "tasks/addTask.html", {
                "form": form # send back what they submitted so they can see whats wrong
            })
    return render(request,"tasks/addTask.html", {
        "form": NewTaskForm() 
    })

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>just a little testerino</h1>
</body>
</html>

lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is It Newyears?</title>

    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if answer %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

lecture3/tasks/templates/tasks/addTask.html
{% extends 'tasks/layout.html' %}

{% block body %}

<h2>Add Task</h2>
<form action="{% url 'tasks:addTask' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
</form>

<a href="{% url 'tasks:index' %}">Back to Tasks</a>


{% endblock %}

lecture3/tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}


{% block body %}
<h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>

            <!-- django allows inside of for loops to allow for a condition where
                 if the list is empty, do this action instead -->
        {% empty %}
            <li>No Tasks!</li>
        {% endfor %}
    </ul>

    <a href="{% url 'tasks:addTask' %}">Add a Task</a>
{% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    
    {% block body %}
    {% endblock %}

</body>
</html>